name: GNU (macOS)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install gfortran and binutils
      run: brew install gcc binutils

    - name: NumPy
      run: python3 -m pip install numpy --break-system-packages

    - name: Clone DL_PY2F
      working-directory: ${{github.workspace}}/example
      run: git clone https://github.com/stfc/dl_py2f.git dl_py2f

    - name: mkdir
      working-directory: ${{github.workspace}}/example
      run: mkdir build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/example/build
      run: cmake -DFROM_SOURCE:BOOL=TRUE -DCMAKE_Fortran_FLAGS="-g" ${{github.workspace}}/example
      env:
        FC: gfortran-14
        CXX: g++-14

    - name: Build
      working-directory: ${{github.workspace}}/example/build
      run: make

    - name: Test
      working-directory: ${{github.workspace}}
      run: |
        set -o pipefail
        python3 user_script.py
      env:
        PYTHONPATH: ${{github.workspace}}

    - name: DWARF regression test
      working-directory: ${{github.workspace}}
      run: python3 .github/workflows/test_dwarf.py example/build/lib/libexample.dylib example/build/modules/yourmodule.mod
      env:
        PYTHONPATH: ${{github.workspace}}
